-- Rest of Mathias's Powder Mage trilogy (2026-09-02): Promise of Blood
-- (#1) was already in the catalog and tagged; these 2 sequels were
-- confirmed missing while updating his ratings after a qualitative
-- recommend() review (see docs/project-log.md). Bibliographic data only,
-- not tagged -- can't be rated/scored until tagged, same as any other
-- untagged book. Series already exists (Powder Mage, hardcover_id 2962,
-- created when Promise of Blood was first ingested), so no new series row.

insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Autumn Republic', 'Brian McClellan', '031621910X', 'https://assets.hardcover.app/edition/14262123/138a12efc83617a58d45d7af92677110892fffa5.jpeg', '"Field Marshal Tamas returns to his beloved country to find that for the first time in history, the capital city of Adro lies in the hands of a foreign invader. His son is missing, his allies are indistinguishable from his foes, and reinforcements are several weeks away ... With the Kez still bearing down upon them and without clear leadership, the Adran army has turned against itself. Inspector Adamat is drawn into the very heart of this new mutiny with promises of finding his kidnapped son .. And Taniel Two-shot, hunted by men he once thought his friends, must safeguard the only chance Adro has of getting through this war without being destroyed"--Dust jacket flap.', 582, null, 2015, 437920, (select id from series where hardcover_id = 2962), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Crimson Campaign', 'Brian McClellan', '0356522245', 'https://assets.hardcover.app/edition/21716912/eed4b69f73335de7189e541ae944dcc0ab436dcd.jpeg', '''The hounds at our heels will soon know we are lions.'' Tamas''s invasion of Kez ends in disaster when a Kez counter-offensive leaves him cut off behind enemy lines with only a fraction of his army, no supplies and no hope of reinforcements. Drastically outnumbered and pursued by the enemy''s best, he must lead his men on a reckless march through northern Kez to safety, and back over the mountains so that he can defend his country from an angry god. In Adro, Inspector Adamat only wants to rescue his wife. To do so he must track down and confront the evil Lord Vetas. He has questions for Vetas concerning his enigmatic master, but the truth is darker than he could have imagined. With Tamas and his powder cabal presumed dead, Taniel Two-shot finds himself alongside the god Mihali as the last line of defence against Kresimir''s advancing army. Tamas''s generals bicker among themselves, the brigades lose ground every day beneath the Kez onslaught and Kresimir wants the head of the man who shot him in the eye.', 608, 1202, 2014, 437922, (select id from series where hardcover_id = 2962), '2') on conflict (hardcover_id) do nothing;
