-- Targeted ingestion round 2 (2026-09-02): 21 new books, bibliographic data
-- only, deliberately NOT tagged yet -- 16 are direct sequels a real rater
-- (Mathias) named in his ratings history that a docs consistency pass found
-- missing (see docs/project-log.md's "corrects a stale earlier entry" and
-- "expanded the catalog" entries); the other 5 are famous/classic titles
-- found missing during a broader breadth check across subgenres (2 more
-- candidates from that check, Good Omens and Babel, turned out to already
-- be in the catalog under their full subtitle -- confirmed via hardcover_id,
-- not re-inserted). Generated from scripts/ingest-targeted-titles-2.js's run
-- against local -- see that file for the confirmed hardcover_id per title.

-- 4 new series (hardcover-sourced)
insert into series (name, status, book_count, hardcover_id) values ('The Belgariad', 'ongoing', 19, 1133) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('The Chronicles of Prydain', 'ongoing', 27, 5608) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('Shannara (Chronological Order)', 'ongoing', 105, 10115) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('London Below', 'ongoing', 2, 203030) on conflict (hardcover_id) do nothing;

-- 21 new books
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Broken Eye', 'Brent Weeks', '8415831145', 'https://assets.hardcover.app/external_data/3372189/33e81d3d1bb8ef700e36c07922e8a096ec42fed6.jpeg', 'Without the protection of Gavin Guile, who has been captured and enslaved and has lost his powers, Kip, Teia, and Karris fight to survive a secret war between the nobles, rebels, and an ancient order of stealthy assassins called The Broken Eye.', 864, 1773, 2014, 12127, (select id from series where hardcover_id = 5547), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Emperor of Thorns', 'Mark Lawrence', '0425256855', 'https://assets.hardcover.app/edition/12721241/5e094ec77d025ee99460267f25a6b65c92de70cf.jpeg', 'The path to the throne is broken – only the broken can walk it.

The world is cracked and time has run through, leaving us clutching at the end days. These are the days that have waited for us all our lives. These are my days. I will stand before the Hundred and they will listen. I will take the throne no matter who stands against me, living or dead, and if I must be the last emperor then I will make of it such an ending.

This is where the wise man turns away. This is where the holy kneel and call on God. These are the last miles, my brothers. Don’t look to me to save you. Run if you have the wit. Pray if you have the soul. Stand your ground if courage is yours. But don’t follow me.

Follow me, and I will break your heart.', 592, 827, 2013, 36790, (select id from series where hardcover_id = 5596), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Grey Sister', 'Mark Lawrence', '1101988894', 'https://assets.hardcover.app/edition/18877284/33bafb57c13806e65561b310bd8cfadb279a203d.jpeg', 'In Mystic Class Nona Grey begins to learn the secrets of the universe. But so often, knowing the truth just makes our choices harder. Before she leaves the Convent of Sweet Mercy, Nona must choose her path and take the red of a Martial Sister, the grey of a Sister of Discretion, the blue of a Mystic Sister or the simple black of a Bride of the Ancestor, entailing a life of prayer and service.

Standing between her and these choices are the pride of a thwarted assassin, the ambition of a would-be empress wielding the Inquisition like a blade, and the vengeance of the empire’s richest lord.

As the world narrows around her, and her enemies attack her using the very system she has sworn to, Nona must forge her own path in spite of the pulls of friendship, revenge, ambition, and loyalty.

In all this only one thing is certain. There will be blood.', 415, 962, 2018, 60229, (select id from series where hardcover_id = 5499), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Neverwhere', 'Neil Gaiman', '1472234502', 'https://assets.hardcover.app/external_data/4181202/a0e8ff63af8e1f8812e1a47a0e1755f944cd30d1.jpeg', 'Richard Mayhew is a young man with a good heart and an ordinary life, which is changed forever when he stops to help a girl he finds bleeding on a London sidewalk. His small act of kindness propels him into a world he never dreamed existed. There are people who fall through the cracks, and Richard has become one of them. And he must learn to survive in this city of shadows and darkness, monsters and saints, murderers and angels, if he is ever to return to the London that he knew.', 464, 828, 1996, 65400, (select id from series where hardcover_id = 203030), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Book of Three', 'Lloyd Alexander', '0006725619', 'https://assets.hardcover.app/edition/17028768/415a58c330b5f524b8c4f88b455288f0c7f40375.jpeg', 'Taran dreams of adventure, but nothing exciting ever happens to an Assistant Pig-Keeper, until his pig runs away. A chase through the woods leads Taran far from home and into great danger, for evil prowls the land of Prydain. With a collection of strange and wonderful friends whom he meets on his journey, Taran finds himself fighting so that good may triumph over evil, and so that his beloved home will not fall to a diabolical fiend.', 224, null, 1964, 71845, (select id from series where hardcover_id = 5608), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Pawn of Prophecy', 'David Eddings', '0552148075', 'https://assets.hardcover.app/editions/30773959/4755353132709208.jpg', 'A magnificent epic set against a history of seven thousand years of the struggles of Gods and Kings and men - of strange lands and events - of fate and a prophecy that must be fulfilled! THE BELGARIAD

Long ago, so the Storyteller claimed, the evil God Torak sought dominion and drove men and Gods to war. But Belgarath the Sorcerer led men to reclaim the Orb that protected men of the West. So long as it lay at Riva, the prophecy went, men would be safe.

But that was only a story, and Garion did not believe in magic dooms, even though the dark man without a shadow had haunted him for years. Brought up on a quiet farm by his Aunt Pol, how could he know that the Apostate planned to wake dread Torak, or that he would be led on a quest of unparalleled magic and danger by those he loved - but did not know? For a while his dreams of innocence were safe, untroubled by knowledge of his strange heritage. For a little while... THUS BEGINS BOOK ONE OF THE BELGARIAD', 400, 614, 1982, 82110, (select id from series where hardcover_id = 1133), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Blood Mirror', 'Brent Weeks', '0356504603', 'https://assets.hardcover.app/external_data/60260838/1855e84d8914957cf81fc5a3373d5b1d755a1d6c.jpeg', 'The Blood Mirror is the action-packed fourth novel in the Lightbringer series by international bestseller Brent Weeks. The Seven Satrapies have collapsed into four - and those are falling before the White King''s armies. Gavin Guille, ex-emperor, ex-Prism, ex-galley slave, formerly the one man who might have averted war, is now lost, broken and trapped in a prison crafted by his own magical genius. But Gavin has no magic at all. Worse, in this prison, he may not be alone. Who will fight to prevent a tainted empire from becoming something even worse? ''Brent Weeks is so good it''s beginning to tick me off'' Peter V. Brett ''Weeks has a style of immediacy and detail that pulls the reader relentlessly into the story. He doesn''t allow you to look away'' Robin Hobb ''I was mesmerised from start to finish. Unforgettable characters, a plot that kept me guessing, non-stop action and the kind of in-depth storytelling that makes me admire a writer''s work'' Terry Brooks ''Weeks has truly cemented his place among the great epic fantasy writers of our time'' British Fantasy Society Books by Brent Weeks Night Angel The Way of Shadows Shadow''s Edge Beyond the Shadows Perfect Shadow (novella) Lightbringer The Black Prism The Blinding Knife The Broken Eye The Blood Mirror The Burning White', 682, null, 2015, 86440, (select id from series where hardcover_id = 5547), '4') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Core', 'Peter V. Brett', '837964297X', 'https://assets.hardcover.app/edition/12132819/963c2f3173411f9b04ac62601450198d07d793e0.jpeg', '"New York Times bestselling author Peter V. Brett brings one of the most imaginative fantasy sagas of the twenty-first century to an epic close. For time out of mind, bloodthirsty demons have stalked the night, culling the human race to scattered remnants dependent on half-forgotten magics to protect them. Then two heroes arose--men as close as brothers, yet divided by bitter betrayal. Arlen Bales became known as the Warded Man, tattooed head to toe with powerful magic symbols that enable him to fight demons in hand-to-hand combat--and emerge victorious. Jardir, armed with magically warded weapons, called himself the Deliverer, a figure prophesied to unite humanity and lead them to triumph in Sharak Ka--the final war against demonkind. But in their efforts to bring the war to the demons, Arlen and Jardir have set something in motion that may prove the end of everything they hold dear--a swarm. Now the war is at hand, and humanity cannot hope to win it unless Arlen and Jardir, with the help of Arlen''s wife, Renna, can bend a captured demon prince to their will and force the devious creature to lead them to the Core, where the Mother of Demons breeds an inexhaustible army. Trusting their closest confidantes, Leesha, Inevera, Ragen, and Elissa, to rally the fractious people of the Free Cities and lead them against the swarm, Arlen, Renna, and Jardir set out on a desperate quest into the darkest depths of evil--from which none of them expects to return alive. Look for Peter V. Brett''s complete Demon Cycle: THE WARDED MAN, THE DESERT SPEAR, THE DAYLIGHT WAR, THE SKULL THRONE, THE CORE Praise for the novels of Peter V. Brett The Warded Man "There is much to admire in Peter Brett''s writing, and his concept is brilliant. There''s action and suspense all the way."--Terry Brooks "[A] fast-paced and thoroughly enjoyable dark fantasy."--The Miami Herald The Desert Spear "Inspired, compelling, and totally addictive: the most significant and cinematic fantasy epic since The Lord of the Rings."--Paul W. S. Anderson, director of Resident Evil: Afterlife "Fans of epic fantasy in the tradition of Robert Jordan and George R. R. Martin will enjoy the arrival of a strong voice in multivolume epic fantasy."--Library Journal The Daylight War "Highly entertaining, fast-paced, and action-packed."--SF Site "[Brett is] at the top of his game."--Tor.com The Skull Throne "Heart-thumping, adrenaline-pumping. The crescendo is near perfect."--Book Frivolity "A page-turner, and quite possibly the best so far."--Starburst Magazine"--

"The epic fantasy saga of humans winnowed to the point of extinction by night-stalking demons, and the survivors who fight back. The New York Times bestselling Demon Cycle series comes to its epic conclusion"--', 781, null, 2017, 225783, (select id from series where hardcover_id = 5555), '5') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Handmaid’s Tale', 'Margaret Atwood', '9513198391', 'https://assets.hardcover.app/edition/20879993/7be97c9457dd0572c4cf915cddc844a91a24dc24.jpeg', 'The Handmaid''s Tale is a novel of such power that the reader will be unable to forget its images and its forecast. Set in the near future, it describes life in what was once the United States and is now called the Republic of Gilead, a monotheocracy that has reacted to social unrest and a sharply declining birthrate by reverting to, and going beyond, the repressive intolerance of the original Puritans. The regime takes the Book of Genesis absolutely at its word, with bizarre consequences for the women and men in its population.

The story is told through the eyes of Offred, one of the unfortunate Handmaids under the new social order. In condensed but eloquent prose, by turns cool-eyed, tender, despairing, passionate, and wry, she reveals to us the dark corners behind the establishment’s calm facade, as certain tendencies now in existence are carried to their logical conclusions. The Handmaid''s Tale is funny, unexpected, horrifying, and altogether convincing. It is at once scathing satire, dire warning, and a tour de force.', 324, null, 1985, 377799, (select id from series where hardcover_id = 1009), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Desert Spear', 'Peter V. Brett', '3641049873', 'https://assets.hardcover.app/books/381693/9906224-L.jpg', 'The sun is setting on humanity. The night now belongs to voracious demons that arise as the sun sets, preying upon a dwindling population forced to cower behind ancient and half-forgotten symbols of power. These wards alone can keep the demons at bay, but legends tell of a Deliverer: a general--some would say prophet--who once bound all mankind into a single force that defeated the demons. Those times, if they ever existed, are long past. The demons are back, and the return of the Deliverer is just another myth . . . or is it?Out of the desert rides Ahmann Jardir, who has forged the warlike desert tribes of Krasia into a demon-killing army. He has proclaimed himself Shar''Dama Ka, the Deliverer, and he carries ancient weapons--a spear and a crown--that give credence to his claim. Sworn to follow the path of the first Deliverer, he has come north to bring the scattered city-states of the green lands together in a war against demonkind--whether they like it or not.    But the northerners claim their own Deliverer. His name was Arlen, but all know him now as the Warded Man: a dark, forbidding figure whose skin is tattooed with wards so powerful they make him a match for any demon. The Warded Man denies that he is the Deliverer, but his actions speak louder than words, for he teaches men and women to face their fears and stand fast against the creatures that have tormented them for centuries.Once the Shar''Dama Ka and the Warded Man were friends, brothers in arms. Now they are fierce adversaries. Caught between them are Renna, a young woman pushed to the edge of human endurance; Leesha, a proud and beautiful healer whose skill in warding surpasses that of the Warded Man himself; and Rojer, a traveling fiddler whose uncanny music can soothe the demons--or stir them into such frenzy that they attack one another.      Yet as old allegiances are tested and fresh alliances forged, all are blissfully unaware of the appearance of a new breed of demon, more intelligent--and deadly--than any that have come before.From the Hardcover edition.', 609, null, 2010, 381693, (select id from series where hardcover_id = 5555), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Sword of Shannara', 'Terry Brooks', '0345913744', 'https://assets.hardcover.app/edition/7392092/9dfd40e6-4f32-4b80-8489-1d027738d756.jpg', 'Long ago, the wars of the ancient Evil ruined the world. In peaceful Shady Vale, half-elfin Shea Ohmsford knows little of such troubles. But the supposedly dead Warlock Lord is plotting to destroy everything in his wake. The sole weapon against this Power of Darkness is the Sword of Shannara, which can be used only by a true heir of Shannara. On Shea, last of the bloodline, rests the hope of all the races.

Thus begins the enthralling Shannara epic, a spellbinding tale of adventure, magic, and myth.', 736, 1581, 1977, 427307, (select id from series where hardcover_id = 10115), '10') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Calamity', 'Brandon Sanderson', '849069608X', 'https://assets.hardcover.app/editions/30509030/307f546f-4a77-4646-9acc-40ed20ac042f.jpg', 'When Calamity lit up the sky, the Epics were born. David’s fate has been tied to their villainy ever since that historic night. Steelheart killed his father. Firefight stole his heart. And now Regalia has turned his closest ally into a dangerous enemy.

David knew Prof’s secret, and kept it even when Prof struggled to control the effects of his Epic powers. But facing Obliteration in Babilar was too much. Once the Reckoners’ leader, Prof has now embraced his Epic destiny. He’s disappeared into those murky shadows of menace Epics are infamous for the world over, and everyone knows there’s no turning back. . . .

But everyone is wrong. Redemption is possible for Epics—Megan proved it. They’re not lost. Not completely. And David is just about crazy enough to face down the most powerful High Epic of all to get his friend back. Or die trying.', 420, 712, 2001, 427477, (select id from series where hardcover_id = 1038), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Daylight War', 'Peter V. Brett', '8375748544', 'https://assets.hardcover.app/edition/2554471/8c4b5a21ca8d51e6ec18a92a42d5bb2428ba75d5.jpeg', 'Civil war ravages the north and south, battles fought between those who should be working together. It is up to Arlen and Jardir to put aside their differences and bring their people to terms if they are to have any chance of saving their civilisation from demon-rule.', 808, 1608, 2013, 437918, (select id from series where hardcover_id = 5555), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('King of Thorns', 'Mark Lawrence', '1101581263', 'https://assets.hardcover.app/external_data/60961941/18cfef5cdf122b13dabe5a0bfc726dce21cd3bb6.jpeg', 'To reach greatness you must step on bodies, and many brothers lie trodden in my wake. I’ve walked from pawn to player and I’ll win this game of ours, though the cost of it may drown the world in blood…

The land burns with the fires of a hundred battles as lords and petty kings fight for the Broken Empire. The long road to avenge the slaughter of his mother and brother has shown Prince Honorous Jorg Ancrath the hidden hands behind this endless war. He saw the game and vowed to sweep the board. First though he must gather his own pieces, learn the rules of play, and discover how to break them.

A six nation army, twenty thousand strong, marches toward Jorg’s gates, led by a champion beloved of the people. Every decent man prays this shining hero will unite the empire and heal its wounds. Every omen says he will. Every good king knows to bend the knee in the face of overwhelming odds, if only to save their people and their lands. But King Jorg is not a good king.

Faced by an enemy many times his strength Jorg knows that he cannot win a fair fight. But playing fair was never part of Jorg’s game plan.', 467, 868, 2012, 437921, (select id from series where hardcover_id = 5596), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Skull Throne', 'Peter V. Brett', '0804177473', 'https://assets.hardcover.app/edition/30407745/5252de38a70906774f63803d273fdec738b2f321.jpeg', 'In the grand tradition of George R.R. Martin and Robert Jordan, Sunday Times bestselling author Peter V. Brett continues his critically acclaimed Demon Cycle with the next dramatic instalment: THE SKULL THRONE. The Skull Throne of Krasia stands empty. Built from the skulls of fallen generals and demon princes, it is a seat of honour and ancient, powerful magic, keeping the demon corelings at bay. From atop the throne, Ahmann Jardir was meant to conquer the known world, forging its isolated peoples into a unified army to rise up and end the demon war once and for all. But Arlen Bales, the Painted Man, stood against this course, challenging Jardir to a duel he could not in honour refuse. Rather than risk defeat, Arlen cast them both from a precipice, leaving the world without a saviour, and opening a struggle for succession that threatens to tear the Free Cities of Thesa apart. In the south, Inevera, Jardir''s first wife, must find a way to keep their sons from killing one another and plunging their people into civil war as they strive for enough glory to make a claim on the throne. In the north, Leesha Paper and Rojer Inn struggle to forge an alliance between the duchies of Angiers and Miln against the Krasians before it is too late. Caught in the crossfire is the duchy of Lakton - rich and unprotected, ripe for conquest. All the while, the corelings have been growing stronger, and without Arlen and Jardir there may be none strong enough to stop them. Only Renna Bales may know more about the fate of the missing men, but she, too, has disappeared...', 768, 1434, 2015, 441058, (select id from series where hardcover_id = 5555), '4') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Lady of the Lake', 'Andrzej Sapkowski, David   French', '615555529X', 'https://assets.hardcover.app/edition/30641037/67656100-d2cb-4047-ac7d-ab05eade3458.jpg', 'Trapped in a world ruled by the Elves, separated from Geralt and her destiny, Ciri will need all her training as a fighter and sorceress to survive in the fifth novel of the Witcher, Andrzej Sapkowski’s groundbreaking epic fantasy series that inspired the hit Netflix show and the blockbuster video games.

After walking through the portal in the Tower of Swallows and narrowly escaping death, Ciri finds herself in a completely different world. . . an Elven world. Time does not seem to exist and there are no obvious borders or portals to cross back into her home world. 

She is trapped. But this is the child of prophecy, and she will not be defeated. She knows she must escape to finally rejoin the Witcher and his companions—and also to conquer her worst nightmare. Leo Bonhart, the man who chased, wounded, and tortured Ciri, is still on her trail. And the world is still at war.', 560, 1218, 1999, 445169, (select id from series where hardcover_id = 1808), '5') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Burning White', 'Brent Weeks', '1549154818', 'https://assets.hardcover.app/edition/3389994/1dcf6b59c75acdd14821152741bba2d3158c71d9.jpeg', 'In the stunning conclusion to the epic, New York Times bestselling Lightbringer series by Brent Weeks, kingdoms clash as Kip must finally escape his family''s shadow in order to protect the land and people he loves. Gavin Guile, once the most powerful man the world had ever seen, has been laid low. He''s lost his magic, and now he is on a suicide mission. Failure will condemn the woman he loves. Success will condemn his entire empire. As the White King springs his great traps and the Chromeria itself is threatened by treason and siege, Kip Guile must gather his forces, rally his allies, and scramble to return for one impossible final stand. The long-awaited epic conclusion of Brent Weeks''s New York Times bestselling Lightbringer series. Lightbringer The Black Prism The Blinding Knife The Broken Eye The Blood MirrorThe Burning White For more from Brent Weeks, check out: Night Angel The Way of Shadows Shadow''s Edge Beyond the Shadows The Night Angel Trilogy: 10th Anniversary EditionNight Angel: The Complete Trilogy (omnibus) Perfect Shadow: A Night Angel Novella The Way of Shadows: The Graphic Novel', 992, null, 2019, 446514, (select id from series where hardcover_id = 5547), '5') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Holy Sister', 'Mark Lawrence', '0008152403', 'https://assets.hardcover.app/external_data/40704725/623093bffb1d308a1d7ae677ffecc0ce9c5d1cba.jpeg', 'They came against her as a child. Now they face the woman. 

The ice is advancing, the Corridor narrowing, and the empire is under siege from the Scithrowl in the east and the Durns in the west. Everywhere, the emperor’s armies are in retreat. 

Nona Grey faces the final challenges that must be overcome if she is to become a full sister in the order of her choice. But it seems unlikely that she and her friends will have time to earn a nun’s habit before war is on their doorstep. 

Even a warrior like Nona cannot hope to turn the tide of war.

The shiphearts offer strength that she might use to protect those she loves, but it’s a power that corrupts. A final battle is coming in which she will be torn between friends, unable to save them all. A battle in which her own demons will try to unmake her. 

A battle in which hearts will be broken, lovers lost, thrones burned.', 336, 834, 2019, 446805, (select id from series where hardcover_id = 5499), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Rise of Empire', 'Michael J. Sullivan', '1464036128', 'https://assets.hardcover.app/edition/30806807/ef73285c-0f73-4e2d-a393-6286599480e2.jpg', 'War has come to Melengar and once more Royce and Hadrian are hired to make a desperate gamble and form an alliance with the Nationalists whom are fighting the Imperialists in the south. As the power of the Nyphron Empire grows, so does Royce''s suspicion that the wizard Esrahaddon is using the thieves as pawns in his own grab for power. To find the truth, he must unravel the secret of Hadrian''s past--what he discovers may end their friendship and break Riyria in two.', 802, 1589, 2009, 462825, (select id from series where hardcover_id = 5843), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Blinding Knife', 'Brent Weeks, Simon Vance', '035652244X', 'https://assets.hardcover.app/edition/30414622/09bd5219a4bccb14d1d9d744031d13d2d7f73815.jpeg', 'With 50,000 refugees, a bastard son, and an ex-fiance who may have learned his darkest secret, Gavin has problems on every side. All magic in the world is running wild and threatens to destroy the Seven Satrapies.', null, 1393, 2012, 477964, (select id from series where hardcover_id = 5547), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Valor', 'John Gwynne', '0330545760', 'https://assets.hardcover.app/edition/30417272/8092edac597f2017a80fa7444bac297382e6ad0a.jpeg', 'Corban flees his homeland searching for peace, but he soon discovers that there is no haven in the west as the agents of Rhin and roaming bands of giants hound his every step.

Veradis leaves the battleground and rushes to his King''s side. But he has witnessed both combat and betrayal and his duty weighs heavily upon him.

Maquin seeks only revenge, but pirate slavers and the brutal world of pit-fighting stand in his way.

Nathair becomes embroiled in the wars of the west as Queen Rhin marches against King Owain. The need to find the cauldron of the giants drives him on.

Sides are chosen and oaths will be fulfilled or broken in a land where hell has broken loose.', 649, 1424, 2014, 478363, (select id from series where hardcover_id = 2438), '2') on conflict (hardcover_id) do nothing;
