-- Targeted ingestion (2026-09-03): bibliographic data only, NOT tagged --
-- 23 books the repo owner (Mathias) named as titles he remembers reading
-- and rated (loved/liked/disliked/hated), confirmed missing from the
-- catalog by checking against local first (see below for the ones that
-- turned out to already be present). Each hardcover_id below was
-- confirmed via a search-only pass first, not auto-matched -- generated
-- from scripts/_scratch-gen-migration.js's run against local (not
-- committed, a one-off scratch script; see docs/project-log.md for the
-- per-book confirmation notes).
--
-- Already in the catalog, so NOT re-inserted here (bibliographic data
-- only, ratings handled separately in data/ratings/mathias.json):
--   - Valor (John Gwynne, Faithful and the Fallen #2, hardcover_id
--     478363) -- confirmed already present.
--   - Ender's Shadow (Orson Scott Card, hardcover_id 264175) -- already
--     present AND already rated 'loved'.
--   - The Shadow of What Was Lost (James Islington, Licanius #1,
--     hardcover_id 445584) -- already present AND already rated 'liked'.
--   - The Light of All That Falls (James Islington, Licanius #3,
--     hardcover_id 441085) -- already present but NOT yet rated; rating
--     added to mathias.json, no insert needed here.
--   - Kings of Paradise (Richard Nell, hardcover_id 433544) -- already
--     present and already rated 'loved'; deliberately not touched.
--     Note: its series_id is NULL (Hardcover's own record for this book
--     also has no featured_series), so it's NOT linked to the new
--     'Ash and Sand' series row created below even though its two
--     sequels are -- flagged in project-log.md as an optional follow-up
--     for the repo owner, not fixed here since fixing an existing row
--     wasn't asked for.
--
-- Disambiguations worth noting explicitly:
--   - "Valor" is John Gwynne's (Faithful and the Fallen #2), not Brian
--     McClellan's -- per repo owner's own correction.
--   - "The Malice" (hardcover_id 481926, Peter Newman, The Vagrant #2)
--     is a DIFFERENT book from "Malice" (hardcover_id 429071, John
--     Gwynne, Faithful and the Fallen #1) already in the catalog --
--     confirmed distinct hardcover_id/author/series before inserting;
--     both titles now coexist.
--   - "I'm Afraid You've Got Dragons" was named as Peter McLean's but is
--     actually Peter S. Beagle's (2024, hardcover_id 1086185) -- no
--     Peter McLean book by this title exists on Hardcover (searched
--     directly, and confirmed via cached_contributors on every
--     candidate id). Treated the same way as the Valor/McClellan
--     correction above: trusted the title match over the misattributed
--     author. Flagged for the repo owner in case this isn't actually
--     the book he meant.
--   - "The Wandering Inn": Hardcover represents this ongoing web serial
--     as many individual volume entries plus one primary series entry.
--     Picked hardcover_id 446694 (title "The Wandering Inn", the
--     highest-popularity entry, users_count 903, tagged as series
--     position #1) as the single representative entry per the task's
--     instruction to prefer one sensible entry over adding dozens of
--     volumes -- not the "(Web)" variant volumes, which are a separate,
--     lower-popularity parallel listing of the same content.
--
-- Author-field contamination stripped (narrator names dropped, per
-- CLAUDE.md's data-quality section) before inserting:
--   - "Prince of Fools" (hardcover_id 159149): Hardcover's author_names
--     included "Tim Gerard Reynolds" (audiobook narrator) -- inserted
--     as 'Mark Lawrence' only.
--   - "Blackwing" (hardcover_id 445518): Hardcover's author_names
--     included "Colin Mace" (audiobook narrator) -- inserted as
--     'Ed McDonald' only.
--
-- New series created (hardcover-sourced): Ash and Sand, The Lot Lands,
-- Covenant of Steel, Iconoclasts, The Vagrant, Empire of the Wolf,
-- The Wandering Inn, The Red Queen's War, Raven's Mark, Time Master,
-- Impossible Times.
--
-- Deliberately NOT rated in data/ratings/mathias.json even though
-- inserted here: "One Word Kill" (Mark Lawrence, Impossible Times #1,
-- hardcover_id 427996) -- the repo owner said only "didn't resonate
-- well with me", which doesn't map unambiguously to one of the 5 rating
-- labels (disliked vs it_was_okay are both plausible). Bibliographic
-- data added so it's ready to tag/rate once he specifies which.
--
-- Deliberately NOT added at all (sequels not asked for): Iconoclasts
-- #2/#3 (only Aching God was named), Raven's Mark #2+ (only Blackwing
-- was named), The Vagrant #3 "The Seven" (only books 1-2 were named).

-- New series
insert into series (name, status, book_count, hardcover_id) values ('Ash and Sand', 'ongoing', 2, 1470) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('The Lot Lands', 'ongoing', 3, 7439) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('Covenant of Steel', 'ongoing', 3, 7637) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('Iconoclasts', 'ongoing', 3, 7678) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('The Vagrant', 'ongoing', 10, 1821) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('Empire of the Wolf', 'ongoing', 4, 6763) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('The Wandering Inn', 'ongoing', 25, 12714) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('The Red Queen''s War', 'ongoing', 8, 5710) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('Raven''s Mark', 'ongoing', 5, 6592) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('Time Master', 'ongoing', 10, 11633) on conflict (hardcover_id) do nothing;
insert into series (name, status, book_count, hardcover_id) values ('Impossible Times', 'ongoing', 3, 1019) on conflict (hardcover_id) do nothing;

-- Books
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Kings of Ash', 'Richard Nell', '1795514000', 'https://assets.hardcover.app/external_data/23611488/c731b7d9044e0775363e9c4a00e293cdddf3db21.jpeg', 'The much anticipated continuation of the Ash and Sand trilogy...Follow the long, bloody journey of Ruka, son of Beyla through the islands of Pyu and the frozen wastes of the Ascom; see the return home of Ratama Kale Alaku, the ''Sorcerer-Prince'', and the terrifying rise of his ''miracles''. Before the end, a shocking history will unravel, ancient connections unfold, and all will learn the cost of unleashing the Kings of Ash...', 514, 1616, 2017, 507299, (select id from series where hardcover_id = 1470), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Kings of Heaven', 'Richard Nell', '9798676270391', 'https://assets.hardcover.app/edition/30458447/55269c35967b0e54884244c4ee4f016558ee62bc.jpeg', 'In the final book of the Ash and Sand trilogy, Ruka, son of Beyla, faces the emperor of the world, yet even victory may not save his people...With the death of his ally, Farahi Alaku, Ruka ''Godtongue'' is alone. Or not exactly... The island prince Kale Alaku now haunts his mind, rattling within his once peaceful ''Grove'', promising revenge and growing every moment in power. Meanwhile, the Pyu isles are in chaos; the coastal kingdom of the Tong is still Ruka''s enemy, and every day that passes brings the empire closer to destroying his dream of a new world for his people.Once again, the son of Beyla will need the strength of his dark twin, Bukayag. Perhaps together they can unite three peoples, gather an army of ash, and defend or destroy their way to peace. But in the end, there can be only one king of heaven...', 410, null, 2020, 507224, (select id from series where hardcover_id = 1470), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Grey Bastards', 'Jonathan French', '0988284553', 'https://assets.hardcover.app/external_data/60212117/67d981284f729a3260b2cd7731d191f60f36d7f3.jpeg', '“[A] fantasy masterwork . . . a dirty, blood-soaked gem of a novel [that reads] like Mad Max set in Tolkien’s Middle-earth.”—Kirkus Reviews (starred review) Jackal and his fellow half-orcs patrol the barren wastes of the Lot Lands, spilling their own damned blood to keep civilized folk safe. A rabble of hard-talking, hog-riding, whore-mongering brawlers they may be, but the Grey Bastards are Jackal’s sworn brothers, fighting at his side in a land where there’s no room for softness. And once Jackal’s in charge—as soon as he can unseat the Bastards’ tyrannical, seemingly unkillable founder—there’s a few things they’ll do different. Better. Or at least, that’s the plan. Until the fallout from a deadly showdown makes Jackal start investigating the Lot Lands for himself. Soon, he’s wondering if his feelings have blinded him to ugly truths about this world, and the Bastards’ place in it. In a quest for answers that takes him from decaying dungeons to the frontlines of an ancient feud, Jackal finds himself battling invading orcs, rampaging centaurs, and grubby human conspiracies alike—along with a host of dark magics so terrifying they’d give even the heartiest Bastard pause. Finally, Jackal must ride to confront a threat that’s lain in wait for generations, even as he wonders whether the Bastards can—or should--survive. Delivered with a generous wink to Sons of Anarchy, featuring sneaky-smart worldbuilding and gobs of fearsomely foul-mouthed charm, The Grey Bastards is a grimy, pulpy, masterpiece—and a raunchy, swaggering, cunningly clever adventure that’s like nothing you’ve read before. Praise for The Grey Bastards “Saddle up the war boar and set off on a wild, gory thrill-ride that ends in an awesome climax and begs for a sequel.”—Daily Mail (UK) “Non-stop action, though not for faint hearts . . . the Grey Bastards live up to their name in all respects.”—The Wall Street Journal', 432, 1067, 2015, 445672, (select id from series where hardcover_id = 7439), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The True Bastards', 'Jonathan French', '0356511650', 'https://assets.hardcover.app/edition/30458531/0b5c8297232fea1557814efdd0b50fd253515b98.jpeg', '''AN ADDICTIVELY READABLE - AND UNDENIABLY COOL - FANTASY MASTERWORK'' Kirkus on The Grey Bastards Following the runaway success of Jonathan French''s critically acclaimed fantasy adventure The Grey Bastards comes book two in the Lot Lands series - The True Bastards. LEAD FROM THE SADDLE. DARE TO SURVIVE. Fetching was once the only female rider in the Lot Lands. Now she is the leader of her own hoof, a band of loyal half-orcs sworn to her command. But in the year since she took power, the True Bastards have struggled to survive. Tested to the breaking point by the burdens of leadership, Fetching battles desperately to stave off famine, desertion and the scorn of the other half-orc chieftains, even as orcs and humans alike threaten the Lots'' very existence. Then an old enemy finds a way to strike at her from beyond the grave - and suddenly only one faint hope for salvation remains. A standout adventure fantasy debut that''s down, dirty and damn good fun - perfect for fans of Joe Abercombie, Mark Lawrence, Markus Heitz''s Dwarves series and Stan Nicholl''s Orcs series Praise for The Grey Bastards: ''Flithy, charistmastic and frankly excellent'' Mark Lawrence ''A gritty adventure with a fantastic, foul-mouthed voice . . . Fans of Abercrombie''s the First Law . . . will like this a lot'' Django Wexler ''A bloody good tale of battle, betrayal and war pigs'' Brian McClellan ''Jonathan French has to be lauded for his plot ingenuity, bawdry charm and vicious characters. The Grey Bastards has instantaneously catapulted him into my must-read list'' Fantasy Book Critic ''I''d like to raise a tankard to The Grey Bastards'' brilliance'' Fantasy Faction BRING ON THE ORCS . . .', 592, 1311, 2019, 507293, (select id from series where hardcover_id = 7439), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('An Echo of Things to Come', 'James Islington', '0356507815', 'https://assets.hardcover.app/edition/30407510/cd4c3265730d541a2fe1d93d298d8d3c2d3fa6ab.jpeg', 'DARKNESS FALLS ACROSS A LAND IN DESPERATE NEED OF HEROES An amnesty has been declared for all Augurs - finally allowing them to emerge from hiding and openly oppose the dark forces massing against Andarra. However, as Davian and his new allies hurry north towards the ever-weakening Boundary, fresh horrors along their path suggest that their reprieve may have come far too late. Meanwhile, Caeden continues to wrestle with the impossibly heavy burdens of his past. Yet as more and more of his memories return, he begins to realise that the motivations of the two sides in this ancient war may not be as clear-cut as they first seemed . . .', 608, 1588, 2017, 441081, (select id from series where hardcover_id = 5982), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Pariah', 'Anthony Ryan', '3608121560', 'https://assets.hardcover.app/external_data/25820360/e66978708d6d0fc38f4254ca8903c5d60285a3a5.jpeg', 'Alwyn is a thief and experienced brawler with few friends and an appetite for revenge.  Few would call him handsome, and even his enemies will admit he knows how to survive.  Unfortunately, Alwyn does have a knack for chasing near-death experiences.

Alwyn''s biggest fault is a near-fanatical following of charismatic leaders, especially those whose plans involve violence on a grand scale.  Lady Evadine Courlain is one such leader, whose visions tell of a chaotic future.  One that can only be avoided by destroying the False King''s rebellion.  Alwyn is caught in a war, in which he wants no part.  Fate has other plans.', 576, 1197, 2021, 456527, (select id from series where hardcover_id = 7637), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Martyr', 'Anthony Ryan', '0316430803', 'https://assets.hardcover.app/external_data/4220360/5077221a72d4ce0e474718b958c457272135d7e8.jpeg', '<b>''<i>The Martyr</i> continues the brilliance of <i>The Pariah</i> with more grit and adventure that Anthony Ryan fans and newcomers will devour'' </b><i>Grimdark Magazine</i><br /><br /><b>''Anthony Ryan continues to write incredible, gritty fantasy that ticks every box every time. Perfect Fantasy'' </b><i>FanFiAddict</i><br /><br />Times have changed for Alwyn Scribe. Once an outlaw, he''s now a spymaster and sworn protector of Lady Evadine Courlain, whose visions of a demonic apocalypse have earned her the fanatical devotion of the faithful.<br /><br />Yet Evadine''s growing fame has put her at odds with both Crown and Covenant. As trouble brews in the kingdom, both seek to exploit her position for their own ends.<br /><br />Sent to the Duchy of Alundia to put down a rebellion, Alwyn must rely on old instincts to fight for his new cause. Deadly feuds and ancient secrets are laid bare as war erupts, a war that will decide the fate of the Kingdom of Albermaine and, perhaps, prevent the coming of the prophesied Second Scourge.<br /><br /><b><i>The Martyr</i> is the sequel to <i>The Pariah</i> and continues the ruthless and gripping fantasy epic from <i>New York Times</i> bestseller Anthony Ryan, whose books have sold more than a million copies worldwide.</b><br /><br />Praise for the series<br /><br /><b>''A gritty, heart-pounding tale of betrayal and bloody vengeance'' </b>John Gwynne <br /><br /><b>''<i>The Pariah</i> is Anthony Ryan at his best. A fast-paced, brutal fantasy novel with larger-than-life characters and a plot full of intrigue and suspense'' </b><i>Grimdark Magazine</i><br /><br /><b>''This is Anthony Ryan''s best book yet'' </b>Michael Fletcher<br /><br /><b>''Fantastic writing, an amazing world, a plot that won''t quit, and an unforgettable character . . . Anthony Ryan is one of the best epic fantasy authors out there'' </b>Bookworm Blues<br /><br /><b>''Gritty and well-drawn, this makes a rich treat for George R. R. Martin fans'' </b><i>Publishers Weekly</i> (starred review)', 528, 1182, 2022, 507199, (select id from series where hardcover_id = 7637), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Traitor', 'Anthony Ryan', '360812392X', 'https://assets.hardcover.app/external_data/61878501/16e10ac8b6aeeb0180b005815d3f85a3eb89b575.jpeg', 'In this “gritty, heart-pounding” (John Gwynne) conclusion to the New York Times bestselling fantasy trilogy, The Covenant of Steel, Alwyn must make a difficult decide between his heart and his morals as he prepares for his final battle. It’s been a long journey for Alwyn Scribe. Born a bastard and raised an outlaw, he’s now a knight and the most trusted advisor to Lady Evadine Courlain. Together they’ve won countless battles and helped to bring order to a fractured kingdom. Yet Evadine is not the woman Alwyn once knew. As puritanical fury increasingly replaces her benevolent faith, Alwyn begins to question what her true motives really are. As the kingdom braces itself for one final battle, Alwyn’s conscience fights its own war with his heart. Now, more than ever, he must decide whose side he’s really on. "This makes a rich treat for George R. R. Martin fans." —Publishers Weekly (starred review) on The Pariah', 600, 1155, 2023, 885611, (select id from series where hardcover_id = 7637), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Aching God', 'Mike Shel', '1985746158', 'https://assets.hardcover.app/edition/30411417/11457323-L.jpg', '"Closer, mortal. You are here, finally, to feed the Aching God..." The days of adventure are passed for Auric Manteo. Retired to the countryside and isolated with his scars and riches, he no longer delves into forbidden ruins seeking dark wisdom and treasure. But just as old nightmares begin plaguing his sleep, he receives an urgent summons back to that old life. To save his only daughter, he must return to the place of his greatest trauma: the haunted Barrowlands. Along with a group of inexperienced companions and an old soldier, he must confront the dangers of the ancient and wicked Djao civilization. He has survived fell beasts, insidious traps, and deadly hazards before. But how can he contend with the malice of a bloodthirsty living god? First volume in the planned epic fantasy trilogy Iconoclasts, Aching God is the debut novel by RPG adventure designer Mike Shel. This volume also includes an advanced preview of Iconoclasts - Book II: Sin Eater.', 598, null, 2018, 460094, (select id from series where hardcover_id = 7678), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Vagrant', 'Peter Newman', '0008163308', 'https://assets.hardcover.app/edition/30407144/1373a47826545c056f5cab19824f96c3374b747e.jpeg', 'The Vagrant is his name. He has no other. Friendless and alone he walks across a desolate, war-torn landscape, carrying nothing but a kit-bag, a legendary sword and a baby. His purpose is to reach the Shining City, last bastion of the human race, and deliver the sword, the only weapon that may make a difference in the ongoing war. But the Shining City is far away and the world is a very dangerous place.', 400, 804, 2015, 445619, (select id from series where hardcover_id = 1821), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Malice', 'Peter Newman', '0007593171', 'https://assets.hardcover.app/edition/30421925/8737688-L.jpg', 'Following Peter Newman’s brilliant debut THE VAGRANT, is the much-anticipated sequel THE MALICE.', 371, null, 2016, 481926, (select id from series where hardcover_id = 1821), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Justice of Kings', 'Richard Swan', '0356516407', 'https://assets.hardcover.app/edition/30396986/5661a7d69731b6d8ecdc84dab824f6317f48cb4d.jpeg', 'The Justice of Kings, the first in a new epic fantasy trilogy, follows the tale of Sir Konrad Vonvalt, an Emperor’s Justice – a detective, judge and executioner all in one. As he unravels a web of secrets and lies, Vonvalt discovers a plot that might destroy his order once and for all – and bring down the entire Empire.

As an Emperor''s Justice, Sir Konrad Vonvalt always has the last word. His duty is to uphold the law of the empire using whatever tools he has at his disposal: whether it''s his blade, the arcane secrets passed down from Justice to Justice, or his wealth of knowledge of the laws of the empire. But usually his reputation as one of the most revered—and hated—Justices is enough to get most any job done.

When Vonvalt investigates the murder of a noblewoman, he finds his authority being challenged like never before. As the simple case becomes more complex and convoluted, he begins to pull at the threads that unravel a conspiracy that could see an end to all Justices, and a beginning to lawless chaos across the empire.', 432, 826, 2022, 463029, (select id from series where hardcover_id = 6763), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('I''m Afraid You''ve Got Dragons', 'Peter S. Beagle', '3608988289', 'https://assets.hardcover.app/editions/31110220/358296967751919.jpeg', 'Dragons are common in the backwater kingdom of Bellemontagne, coming in sizes from mouse-like vermin all the way up to castle-smashing monsters. Gaius Aurelius Constantine Heliogabalus Thrax (who would much rather people call him Robert) has recently inherited his deceased dad’s job as a dragon catcher/exterminator, a career he detests with all his heart in part because he likes dragons, feeling a kinship with them, but mainly because his dream has always been the impossible one of transcending his humble origin to someday become a prince’s valet. Needless to say, fate has something rather different in mind…', 224, 481, 2024, 1086185, null, null) on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Wandering Inn', 'pirateaba', null, 'https://assets.hardcover.app/editions/30407805/3125941921004678-41033158.jpg', '"No killing Goblins."So reads the sign outside of The Wandering Inn, a small building run by a young woman named Erin Solstice. She serves pasta with sausage, blue fruit juice, and dead acid flies on request. And she comes from another world. Ours.It''s a bad day when Erin finds herself transported to a fantastical world and nearly gets eaten by a Dragon. She doesn''t belong in a place where monster attacks are a fact of life, and where Humans are one species among many. But she must adapt to her new life. Or die.In a dangerous world where magic is real and people can level up and gain classes, Erin Solstice must battle somewhat evil Goblins, deadly Rock Crabs, and hungry [Necromancers]. She is no warrior, no mage. Erin Solstice runs an inn. She''s an [Innkeeper].', 1235, 2887, 2017, 446694, (select id from series where hardcover_id = 12714), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Prince of Fools', 'Mark Lawrence', '9898869976', 'https://assets.hardcover.app/external_data/42432872/977f7bcbc5fde9cc08107ae5be64e7bbdbdc6253.jpeg', 'Her grandson Jalan Kendeth is a coward, a cheat and a womaniser; and tenth in line to the throne. While his grandmother shapes the destiny of millions, Prince Jalan pursues his debauched pleasures. Until he gets entangled with Snorri ver Snagason, a huge Norse axe man, and dragged against his will to the icy north.

In a journey across half the Broken Empire, Jalan flees minions of the Dead King, agrees to duel an upstart prince named Jorg Ancrath, and meets the ice witch, Skilfar, all the time seeking a way to part company with Snorri before the Norseman’s quest leads them to face his enemies in the black fort on the edge of the Bitter Ice.', null, null, 2014, 159149, (select id from series where hardcover_id = 5710), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Liar’s Key', 'Mark Lawrence', '0425268810', 'https://assets.hardcover.app/edition/30412557/6b6b5ac886cd8397a59daff4cd0c2a7946a86004.jpeg', 'Winter has locked Prince Jalan Kendeth far from the luxury of his southern palace. The North may be home to Viking Snorri ver Snagason but he is just as eager to leave. However, even men who hold a key that can open any door must wait for the thaw.

As the ice unlocks its jaws the Dead King moves to claim what was so nearly his. But there are other players in this game, other hands reaching for Loki’s key.

Jalan wants only to return to the wine and women of the south, but Snorri has a different and terrifying goal. The warrior aims to find the very door into death and throw it wide. Snorri ver Snagason will challenge all of Hell if that’s what it takes to bring his wife and children back into the living world. He has found the key – now all he needs is to find the door.

But pawns are played to sacrifice and the Red Queen set both these men upon her board. How many moves ahead has the Silent Sister seen? How far will they get before their part in the game is over?', 672, 1236, 2015, 446986, (select id from series where hardcover_id = 5710), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Wheel of Osheim', 'Mark Lawrence', '000753163X', 'https://assets.hardcover.app/external_data/34599248/7e107b51c34306f74adc8f8e62d6124048660816.jpeg', 'All the horrors of Hell stand between Snorri Ver Snagason and the rescue of his family, if indeed the dead can be rescued. For Jalan Kendeth, getting back out alive and with Loki''s key is all that matters. Loki''s creation can open any lock, any door, and it may also be the key to Jalan''s fortune back in the living world. Jalan plans to return to the three w''s that have been the core of his idle and debauched life: wine, women, and wagering. Fate however has other plans, larger plans. The Wheel of Osheim is turning ever faster, and it will crack the world unless it''s stopped. When the end of all things looms, and there''s nowhere to run, even the worst coward must find new answers. Jalan and Snorri face many dangers, from the corpse hordes of the Dead King to the many mirrors of the Lady Blue, but in the end, fast or slow, the Wheel of Osheim always pulls you back. In the end it''s win or die.', 673, null, 2016, 302812, (select id from series where hardcover_id = 5710), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Blackwing', 'Ed McDonald', '0399587802', 'https://assets.hardcover.app/edition/4445605/5ba12b61b4b2d215d84913dc98f93c1451b1c74d.jpeg', '"Set on a postapocalyptic frontier, Blackwing is a gritty fantasy debut about a man''s desperate battle to survive his own dark destiny ... Hope, reason, humanity: the Misery breaks them all. Under its cracked and wailing sky, the Misery is a vast and blighted expanse, the arcane remnant of a devastating war with the immortals known as the Deep Kings. The war ended nearly a century ago, and the enemy is kept at bay only by the existence of the Engine, a terrible weapon that protects the Misery''s border. Across the corrupted no-man''s-land teeming with twisted magic and malevolent wraiths, the Deep Kings and their armies bide their time. Watching. Waiting. Bounty hunter Ryhalt Galharrow has breathed Misery dust for twenty bitter years. When he''s ordered to locate a masked noblewoman at a frontier outpost, he finds himself caught in the middle of an attack by the Deep Kings, one that signifies they may no longer fear the Engine. Only a formidable show of power from the very woman he is seeking, Lady Ezabeth Tanza, repels the assault. Ezabeth is a shadow from Galharrow''s grim past, and together they stumble onto a web of conspiracy that threatens to end the fragile peace the Engine has provided. Galharrow is not ready for the truth about the blood he''s spilled or the gods he''s supposed to serve.', null, null, 2017, 445518, (select id from series where hardcover_id = 6592), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('Firestarter', 'Stephen King', '5702700031', 'https://assets.hardcover.app/edition/32537460/eb2e854b-57dc-48ad-803f-efdf969cd8c3.jpg', 'Firestarter is a science fiction-horror thriller novel by Stephen King, first published in September 1980. In July and August 1980, two excerpts from the novel were published in Omni. In 1981, Firestarter was nominated as Best Novel for the British Fantasy Award, Locus Poll Award, and Balrog Award.


----------
Also contained in:
[Ominbus](https://openlibrary.org/works/OL25080326W)', 500, 441, 1980, 382306, null, null) on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Initiate', 'Louise Cooper', '0812533925', 'https://assets.hardcover.app/edition/12299124/8342987-L.jpg', null, 288, null, 1985, 445962, (select id from series where hardcover_id = 11633), '1') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Outcast', 'Louise Cooper', '0812533941', 'https://assets.hardcover.app/edition/29551175/6908189-L.jpg', 'Tarod alone knew the nature of the supernatural force locked within his soul-and he knew that it must be thwarted, no matter what the sacrifice. Denounced by his fellow adepts as a demon, betrayed even by those he loved, he had unleashed a power that twisted the fabric of time, to put himself beyond the reach of that monstrous force and avert the pandemonium that threatened the world. He thought that nothing could break through the barrier he had created. He was wrong...', 222, null, 1986, 445963, (select id from series where hardcover_id = 11633), '2') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('The Master', 'Louise Cooper', '0812533968', 'https://assets.hardcover.app/edition/4201744/6988591-L.jpg', 'In order to defeat Yandros, the Lord of Chaos, Keridil must convene the Conclave of Three, sail to the White Isle shrine, and open Aeoris'' casket.', 184, null, 1987, 325819, (select id from series where hardcover_id = 11633), '3') on conflict (hardcover_id) do nothing;
insert into books (title, author, isbn, cover_url, synopsis, page_count, audiobook_duration_minutes, publication_year, hardcover_id, series_id, position_in_series) values ('One Word Kill', 'Mark Lawrence', '1503903265', 'https://assets.hardcover.app/edition/18765140/96d0784e1d442606f6abedc9394e8452ee74792c.jpeg', 'Ready Player One meets Stranger Things in this new novel by the bestselling author who George RR Martin describes as "an excellent writer." In January 1986, fifteen-year-old boy-genius Nick Hayes discovers he''s dying. And it isn''t even the strangest thing to happen to him that week. Nick and his Dungeons & Dragons-playing friends are used to living in their imaginations. But when a new girl, Mia, joins the group and reality becomes weirder than the fantasy world they visit in their weekly games, none of them are prepared for what comes next. A strange--yet curiously familiar--man is following Nick, with abilities that just shouldn''t exist. And this man bears a cryptic message: Mia''s in grave danger, though she doesn''t know it yet. She needs Nick''s help--now. He finds himself in a race against time to unravel an impossible mystery and save the girl. And all that stands in his way is a probably terminal disease, a knife-wielding maniac and the laws of physics. Challenge accepted.', 197, 404, 2019, 427996, (select id from series where hardcover_id = 1019), '1') on conflict (hardcover_id) do nothing;
