-- Consolidates the pov_count retagging pass (86 books reclassified from
-- the old binary 'multiple' into dual/few/several/ensemble, via 4 batch
-- agents) plus 7 manual corrections to 'single' for books where the
-- agents explicitly found no genuine second recurring POV (American Gods,
-- The Fellowship of the Ring, The Lies of Locke Lamora, and 4 of the
-- earlier Dungeon Crawler Carl books) -- the original binary tagging had
-- floored these at 'multiple' incorrectly; this pass corrected them.

update book_dna set pov_count = 'single' where book_id = (select id from books where title = '11/22/63');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'A Clash of Kings');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'A Clockwork Orange');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'A Court of Mist and Fury');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'A Court of Thorns and Roses');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'A Court of Wings and Ruin');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'A Dance with Dragons');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'A Darker Shade of Magic');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'A Feast for Crows');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'A Game of Thrones');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'A Storm of Swords');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'A Wizard of Earthsea');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'A Wrinkle in Time');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'All Systems Red');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'American Gods');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Annihilation');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Artemis');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Artificial Condition');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Assassin''s Apprentice');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Babel, or The Necessity of Violence: An Arcane History of the Oxford Translators'' Revolution');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Before the Coffee Gets Cold');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Bird Box');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Brave New World');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Caliban''s War');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Carl''s Doomsday Scenario');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Cat''s Cradle');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Catching Fire');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Children of Dune');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Children of Time');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Circe');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'City of Bones');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Dark Matter');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Death''s End');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Divergent');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'Do Androids Dream of Electric Sheep?');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Dune');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Dune Messiah');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Dungeon Crawler Carl');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Edgedancer');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Elantris');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Ender''s Game');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Eragon');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Exit Strategy');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Fahrenheit 451');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Flowers for Algernon');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Foundation');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Fourth Wing');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Frankenstein');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'Gideon the Ninth');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Golden Son');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Harry Potter and the Chamber of Secrets');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Harry Potter and the Deathly Hallows');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Harry Potter and the Goblet of Fire');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Harry Potter and the Half-Blood Prince');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Harry Potter and the Order of the Phoenix');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Harry Potter and the Philosopher''s Stone');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Harry Potter and the Prisoner of Azkaban');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'He Who Fights with Monsters');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'House of Leaves');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Hyperion');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'I Who Have Never Known Men');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'I, Robot');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Interview with the Vampire');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'Iron Flame');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Jade City');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Jonathan Strange & Mr Norrell');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Jurassic Park');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Kings of Paradise');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Klara and the Sun');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Legends & Lattes');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'Leviathan Wakes');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Malice');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Mistborn: The Final Empire');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Morning Star');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Network Effect');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Neuromancer');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Never Let Me Go');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'Ninth House');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'Oathbringer');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Old Man''s War');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'One Hundred Years of Solitude');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Parable of the Sower');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Perdido Street Station');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Piranesi');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Prince of Thorns');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Project Hail Mary');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Ready Player One');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'Recursion');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Red Rising');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'Rhythm of War');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Rogue Protocol');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Sea of Tranquility');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Shadow and Bone');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Shadows of Self');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Six of Crows');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Slaughterhouse-Five');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'Snow Crash');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Station Eleven');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Sunrise on the Reaping');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Tender Is the Flesh');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Alchemist');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Alloy of Law');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Ballad of Songbirds and Snakes');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Bands of Mourning');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Black Company');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Blade Itself');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'The Butcher''s Masquerade');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Colour Of Magic');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Cruel Prince');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Dark Forest');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Dungeon Anarchist''s Cookbook');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'The Eye of the Bedlam Bride');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Eye of the World');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Fellowship of the Ring');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Fifth Season');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Forever War');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Gate of the Feral Gods');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'The Girl with the Dragon Tattoo');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Giver');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Golden Compass');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Gunslinger');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Hero of Ages');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'The Hitchhiker''s Guide to the Galaxy');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Hobbit, or There and Back Again');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The House in the Cerulean Sea');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'The Invisible Life of Addie LaRue');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Last Wish');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'The Left Hand of Darkness');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Lies of Locke Lamora');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Lightning Thief');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Lion, the Witch and the Wardrobe');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'The Long Way to a Small, Angry Planet');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Lost Metal');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Man in the High Castle');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Martian');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Maze Runner');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Midnight Library');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Name of the Wind');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Night Circus');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Ocean at the End of the Lane');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Poppy War');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Priory of the Orange Tree');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Restaurant at the End of the Universe');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Return of the King');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Road');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Sea of Monsters');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'The Silent Patient');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Song of Achilles');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Tainted Cup');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Three-Body Problem');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Time Machine');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'The Two Towers');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Way of Kings');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'The Well of Ascension');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Will of the Many');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'The Wise Man''s Fear');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'This Inevitable Ruin');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'This Is How You Lose the Time War');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Throne of Glass');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Tomorrow, and Tomorrow, and Tomorrow');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Tress of the Emerald Sea');
update book_dna set pov_count = 'single' where book_id = (select id from books where title = 'Twilight');
update book_dna set pov_count = 'few' where book_id = (select id from books where title = 'Warbreaker');
update book_dna set pov_count = 'dual' where book_id = (select id from books where title = 'We Are Legion (We Are Bob)');
update book_dna set pov_count = 'several' where book_id = (select id from books where title = 'Wool');
update book_dna set pov_count = 'ensemble' where book_id = (select id from books where title = 'Words of Radiance');
